### ISSUE TITLE
Participants Section

### ISSUE THREAD

**Issue by Mudit018** [opencodeiiita/Collaborative-Web-2022#116]
Fetch Details from this [API](https://opencode-hook.onrender.com/get-all-data/) and show it on the website.
It should display the name and most of the information of the API.

Add pagination to the rank list since we have a lot of contributors(15 per page).

*Note: Please feel free to add a separate page for each contributor to show their individual contributions. Extra points will be provided if this part is done.*

**Comment by GammaMicrowave** [comment]
claim

**Comment by sushantk1274** [comment]
claim

**Comment by Mudit018** [comment]
@GammaMicrowave What's the status

**Comment by GammaMicrowave** [comment]
Sir changes update kardiye
Badme thoda style sudhar duga jab overall style milega toh
