### ISSUE TITLE
Alignment issue in timer

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Collaborative-Web-2022#132]
Currently the Opencode timer is not properly aligned with the outer circles.  Fix that to display the values vertically and horizontally in center of the outer timer circles.
<img width="1437" alt="Screenshot 2023-01-01 at 10 16 11 PM" src="https://user-images.githubusercontent.com/73935799/210178436-128702c8-1ba9-4464-bf14-962e929b3517.png">

**Comment by Kali-Decoder** [comment]
Claim

**Comment by ananyaa07** [comment]
claim

**Comment by homewardgamer** [comment]
Assigned to @Kali-Decoder
