### ISSUE TITLE
Improve Styling for mobile screens

### ISSUE THREAD

**Issue by Mudit018** [opencodeiiita/Collaborative-Web-2022#136]
You need to improve the styling for mobile screens.
All the styling-related issues are to be handled in this issue.

You can install and use this [extension](https://chrome.google.com/webstore/detail/mobile-simulator-responsi/ckejmhbmlajgoklhgbapkiccekfoccmk) to check for responsiveness and styling in various devices.

*Note: Kindly pull all the changes before making a PR and provide a live link to website*

**Comment by ananyaa07** [comment]
claim
