### ISSUE TITLE
Create a footer for the website

### ISSUE THREAD

**Issue by Mudit018** [opencodeiiita/Collaborative-Web-2022#38]
After all the storage of meta data, now let's get serious with the main website, so here comes an interesting issue:

You need to design the footer of Opencode Collaborative Website.
**Things required in the footer**:

 - Logos of IIITA and GeekHaven on the left side.
 - OpenCode's social media links in the center
   - [Facebook](https://www.facebook.com/opencodeiiita/)
   - [Twitter](https://twitter.com/geekhaveniiita)
   - [GitHub](https://github.com/opencodeiiita)
 - OpenCode's logo is on the right side.

**Comment by ananyaa07** [comment]
claim

**Comment by RibhavBansal** [comment]
claim

**Comment by aasthaaaa7** [comment]
claim

**Comment by Aman1143** [comment]
claim

**Comment by Mudit018** [comment]
@ananyaa07 
If you have any doubt, feel free to ask on the discord server

**Comment by akshayw1** [comment]
claim

**Comment by Kali-Decoder** [comment]
claim

**Comment by Mudit018** [comment]
what's the status @ananyaa07

**Comment by Mudit018** [comment]
If not done till today, the issue will be reassigned

**Comment by ananyaa07** [comment]
@Mudit018 Sir, I have already created the pr for the footer.

**Comment by Mudit018** [comment]
> @Mudit018 Sir, I have already created the pr for the footer.

ok, I'll check

**Comment by ananyaa07** [comment]
@Mudit018 Sir, the live link for the website is :
https://ananyaa07.github.io/Collaborative-Web-2022/opencode.html
