### ISSUE TITLE
Create Project Json file

### ISSUE THREAD

**Issue by Mudit018** [opencodeiiita/Collaborative-Web-2022#43]
Create a ```project.json``` file inside the [data folder](https://github.com/opencodeiiita/Collaborative-Web-2022/tree/main/data).

**Description**: project.json will contain information about the various projects in OpenCode'21.

The following should be the template for each project entry:
```
{
       "name": "Collaborative-Web-2022",
       "description": "Opencode'22 Collaborative website!",
       "repo-url": "https://github.com/opencodeiiita/Collaborative-Web-2022/",
}
```
Tip: Use the opencode22 label to get all repo lists in OpenCode'22.

**Comment by anshgeez31** [comment]
claim

**Comment by pnkvalavala** [comment]
Claim

**Comment by Ayashika** [comment]
claim

**Comment by RibhavBansal** [comment]
claim

**Comment by Aman1143** [comment]
claim

**Comment by aasthaaaa7** [comment]
claim

**Comment by homewardgamer** [comment]
Assigned to @anshgeez31

**Comment by Kali-Decoder** [comment]
claim

**Comment by anshgeez31** [comment]
@homewardgamer sir as I have completed the issue and it has been merged so will you please close this issue so that I can claim other issues
