### ISSUE TITLE
Generate your GitHub resume

### ISSUE THREAD

**Issue by homewardgamer** [opencodeiiita/Collaborative-Web-2022#47]
Generate your GitHub resume by following the instructions in this [repo](https://github.com/resume/resume.github.com).

Create a file named <your-github-username>.json in data > participants

For example: In my case file name would be homewardgamer.json and follow [this](https://github.com/opencodeiiita/Collaborative-Web-2022/blob/main/data/participants/homewardgamer.json) format.

No need to claim, directly create a PR linking this issue

**Comment by pavanvnk** [comment]
Claim
