### ISSUE TITLE
Add Move-to-Top button

### ISSUE THREAD

**Issue by Mudit018** [opencodeiiita/Collaborative-Web-2022#76]
**Note: It should be floating on the bottom right side**

**Comment by iamatifmoin** [comment]
Claim

**Comment by Kali-Decoder** [comment]
Claim

**Comment by terminatorXbgmi** [comment]
Claim

**Comment by iamatifmoin** [comment]
@Mudit018 
This is what the implementation looks like:
[Tab-1672038151516.webm](https://user-images.githubusercontent.com/97212195/209515498-6678df41-a816-40b7-a492-c48e73236edd.webm)

Should I create the PR?

I will remove the coloured divs in the PR. (they were only added to show the functionality)

**Comment by Mudit018** [comment]
> @Mudit018 This is what the implementation looks like: [Tab-1672038151516.webm](https://user-images.githubusercontent.com/97212195/209515498-6678df41-a816-40b7-a492-c48e73236edd.webm)
> 
> Should I create the PR?
> 
> I will remove the coloured divs in the PR. (they were only added to show the functionality)

Yeah, first pull the changes and then accordingly make PR along with a live link to website.

**Comment by Mudit018** [comment]
> @Mudit018 This is what the implementation looks like: [Tab-1672038151516.webm](https://user-images.githubusercontent.com/97212195/209515498-6678df41-a816-40b7-a492-c48e73236edd.webm)
> 
> Should I create the PR?
> 
> I will remove the coloured divs in the PR. (they were only added to show the functionality)

You can also change the button according to the design of the page.

**Comment by Mudit018** [comment]
@iamatifmoin you can now work on this issue

**Comment by Mudit018** [comment]
> @iamatifmoin you can now work on this issue

Make sure to pull all the changes before
