### ISSUE TITLE
Add Timer

### ISSUE THREAD

**Issue by Mudit018** [opencodeiiita/Collaborative-Web-2022#89]
It should show the number of days hours and seconds left in the ending of OpenCode'21.

For ex:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/56023615/209673243-3149fd9d-03e1-450e-9f25-c6dcb83e1ccb.png">

**Comment by harshitgautam2003** [comment]
claim

**Comment by Kali-Decoder** [comment]
Claim

**Comment by sushantk1274** [comment]
claim
