### ISSUE TITLE
Improve Overall Styling

### ISSUE THREAD

**Issue by Mudit018** [opencodeiiita/Collaborative-Web-2022#90]
*Note: You also have to check for responsiveness*

**Comment by iamatifmoin** [comment]
claim

**Comment by iamatifmoin** [comment]
@Mudit018 
Should I wait for more sections to be implemented or should I start?

**Comment by Mudit018** [comment]
@iamatifmoin 
Improve styling till the previous merged issue.
Check for overall responsiveness and also for any specific thing which is not matching or is out of shape in context to the theme.

**Comment by iamatifmoin** [comment]
@Mudit018 
Created PR: #105

**Comment by iamatifmoin** [comment]
@Mudit018 
#118
