### ISSUE TITLE
Implement Project Section

### ISSUE THREAD

**Issue by Mudit018** [opencodeiiita/Collaborative-Web-2022#94]
You need to implement **Project Section**.

Details:
 - Fetch data from [project.json](https://github.com/opencodeiiita/Collaborative-Web-2022/blob/main/data/project.json) and display information.
 - There should be cards for each project.
 - The card should contain the following info:
    - default image for projects
    - a link for each project
    - any detail which you find to be useful
 - Cards should be completely responsive

*Note: Make sure to pull changes before making a PR.*

**Comment by iamatifmoin** [comment]
Claim

**Comment by Mudit018** [comment]
> Claim

Can not assign this issue to you as you already have an ongoing issue in this issue

**Comment by Vishesh-Vijay** [comment]
Claim

**Comment by Mudit018** [comment]
@Vishesh-Vijay You can work on this issue

**Comment by Vishesh-Vijay** [comment]
@Mudit018 sir we can work with bootstrap cards?

**Comment by Mudit018** [comment]
Open for claim

**Comment by ananyaa07** [comment]
claim

**Comment by abhinavs1920** [comment]
Claim

**Comment by Mudit018** [comment]
@ananyaa07 What's the status

**Comment by 88oo** [comment]
claim
