### ISSUE TITLE
Implement Mentor Section

### ISSUE THREAD

**Issue by Mudit018** [opencodeiiita/Collaborative-Web-2022#99]
You need to implement a mentor section while keeping in mind a few things:
 - A card for each mentor should be displayed information about the mentor.
 - The card should be completely responsive.
 - Take reference from [mentors.json](https://github.com/opencodeiiita/Collaborative-Web-2022/blob/main/data/mentors.json) file.
 
*Note: Don't forget to pull the changes before making any PR and the overall responsiveness should be maintained.*

**Comment by aasthaaaa7** [comment]
claim

**Comment by JahnaviGadde** [comment]
claim
